# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a369e76c8c742bfaf9a57fe9addbaccab5a74a43150fa5186f529a78c6a61e12278a6eafb56a0dfe1c48ac9f5d75e3773a28675804ad0ba1a99b7f4e651ca7ab

test:
  secret_key_base: aef15e3d13a00fce264234c092395e58e443e105b4a0f242a32c851e40ced814699b691332f2dfbe7aa9e7e47ba83e983265f93498727de7070a42c5c53b5a17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
